version: '3.9'

services:
  postgres:
    build: ./postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file: .env
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "psql -U $POSTGRES_USER -lqt | cut -d \\| -f 1 | grep -qw $POSTGRES_DB"]
      interval: 2s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: redis:alpine
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 10s
      retries: 5

  django:
    build: ./django
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    env_file: .env
    networks:
      - backend

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      - backend
    volumes:  
      - web-data:/var/www/html

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/db
  web-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/web

networks:
  backend:
    driver: bridge